---------------------
----E_COMMERCE_DB----
---------------------
CREATE DATABASE E_COMMERCE_DB;
USE E_COMMERCE_DB;


-------------------
---CREATE_TABLES---
-------------------


CREATE TABLE CUSTOMER
(
CUSTOMER_ID INT IDENTITY(1,1) PRIMARY KEY,
FULLNAME VARCHAR(150),
EMAIL VARCHAR(150) UNIQUE,
GENDER VARCHAR(10),
DATE_OF_BIRTH DATE,
CITY VARCHAR(50),
COUNTRY VARCHAR(50),
SIGNUP_CHANNEL VARCHAR(50),
SIGNUP_DATE DATE
);



CREATE TABLE CATEGORY
(
CATEGORY_ID INT IDENTITY(1,1) PRIMARY KEY,
CATEGORY_NAME VARCHAR(100)
);

CREATE TABLE BRAND
(
BRAND_ID INT IDENTITY(1,1) PRIMARY KEY,
BRAND_NAME VARCHAR(100)
);
--------------------------------------------
use E_COMMERCE_DB;
alter table CATEGORY ADD URL_IMG VARCHAR(500);
--------------------------------------------


CREATE TABLE SUPPLIER
(
SUPPLIER_ID INT IDENTITY(1,1) PRIMARY KEY,
SUPPLIER_NAME VARCHAR(100),
COUNTRY VARCHAR(100)
);




CREATE TABLE PRODUCT
(
PRODUCT_ID INT IDENTITY(1,1) PRIMARY KEY,
PRODUCT_NAME VARCHAR(50),
TARGET_GENDER VARCHAR(50),
PRICE DECIMAL(10,2),
COST DECIMAL(10,2),
STOCK_QUANTITY INT,
CREATE_DATE DATE,
CATEGORY_ID INT,
BRAND_ID INT,
SUPPLIER_ID INT,

	CONSTRAINT FK_CATEGORY_PRODUCT
		FOREIGN KEY (CATEGORY_ID)
			REFERENCES CATEGORY(CATEGORY_ID),
	CONSTRAINT FK_BRAND_PRODUCT
		FOREIGN KEY (BRAND_ID)
			REFERENCES BRAND(BRAND_ID),
	CONSTRAINT FK_SUPPLIER_PRODUCT
		FOREIGN KEY (SUPPLIER_ID)
			REFERENCES SUPPLIER(SUPPLIER_ID)
);

-------------------------------------------
use E_COMMERCE_DB;
alter table PRODUCT ADD SIZE VARCHAR(5);
--------------------------------------------


CREATE TABLE PROMOTION_TYPE
(
PROMO_TYPE_ID INT IDENTITY(1,1) PRIMARY KEY,
TYPE_NAME VARCHAR(50)
);


CREATE TABLE PROMOTION
(
PROMO_ID INT IDENTITY(1,1) PRIMARY KEY,
CODE VARCHAR(20) UNIQUE,
DISCOUNT_PERCENTAGE DECIMAL(5,2),
START_DATE DATE,
END_DATE DATE,
PROMO_TYPE_ID INT,
	CONSTRAINT FK_PROMP_TYPE_PROMOTION
		FOREIGN KEY (PROMO_TYPE_ID)
			REFERENCES PROMOTION_TYPE(PROMO_TYPE_ID)
);




CREATE TABLE ORDER_STATUS
(
ORDER_STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
STATUS_NAME VARCHAR(30)
);




CREATE TABLE ORDERS
(
ORDER_ID INT IDENTITY(1,1) PRIMARY KEY,
CUSTOMER_ID INT,
PROMO_ID INT,
ORDER_STATUS_ID INT,
ORDER_DATE DATE,
TOTAL_PRICE DECIMAL(10,2),
	CONSTRAINT FK_CUSTOMER_ORDERS
		FOREIGN KEY(CUSTOMER_ID)
			REFERENCES CUSTOMER(CUSTOMER_ID),
	CONSTRAINT FK_PROMO_ORDERS
		FOREIGN KEY (PROMO_ID)
			REFERENCES PROMOTION(PROMO_ID),
	CONSTRAINT FK_ORDER_STATUS_ORDERS
		FOREIGN KEY (ORDER_STATUS_ID)
			REFERENCES ORDER_STATUS(ORDER_STATUS_ID)
);




CREATE TABLE ORDER_ITEMS
(
ORDER_ITEMS_ID INT IDENTITY(1,1) PRIMARY KEY,
ORDER_ID INT,
PRODUCT_ID INT,
QUANTITY INT,
UNIT_PRICE DECIMAL(10,2),
Total_Price AS (Quantity * Unit_Price) PERSISTED,
	CONSTRAINT FK_ORDER_ORDER_ITEMS
		FOREIGN KEY (ORDER_ID)
			REFERENCES ORDERS(ORDER_ID),
	CONSTRAINT FK_PRODUCT_ORDER_ITEMS
		FOREIGN KEY (PRODUCT_ID)
			REFERENCES PRODUCT(PRODUCT_ID)
);





CREATE TABLE PAYMENT_STATUS
(
PAYMENT_STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
STATUS_NAME VARCHAR(50)
);




CREATE TABLE PAYMENT
(
PAYMENT_ID INT IDENTITY(1,1) PRIMARY KEY,
ORDER_ID INT,
PAYMENT_STATUS_ID INT,
AMOUNT DECIMAL(10,2),
METHOD VARCHAR(20),
	CONSTRAINT FK_ORDER_PAYMENT
		FOREIGN KEY (ORDER_ID)
			REFERENCES ORDERS(ORDER_ID),
	CONSTRAINT FK_PAYMENT_STATUS_PAYMENT
		FOREIGN KEY (PAYMENT_STATUS_ID)
			REFERENCES PAYMENT_STATUS(PAYMENT_STATUS_ID)
);



CREATE TABLE SHIPPING_STATUS
(
SHIPPING_STATUS_ID INT IDENTITY(1,1) PRIMARY KEY,
STATUS_NAME VARCHAR(50)
);




CREATE TABLE SHIPPING
(
SHIPPING_ID INT IDENTITY(1,1) PRIMARY KEY,
ORDER_ID INT,
SHIPPING_STATUS_ID INT,
SHIPPING_DATE DATE,
DELIVERY_DATE DATE,
CARRIER VARCHAR(50),
SHIPPING_COST DECIMAL(10,2),
	CONSTRAINT FK_ORDER_SHIPPING
		FOREIGN KEY (ORDER_ID)
			REFERENCES ORDERS(ORDER_ID),
	CONSTRAINT FK_SHIPPING_STATUS_SHIPPING
		FOREIGN KEY (SHIPPING_STATUS_ID)
			REFERENCES SHIPPING_STATUS(SHIPPING_STATUS_ID)
);




CREATE TABLE REVIEW
(
REVIEW_ID INT IDENTITY(1,1) PRIMARY KEY,
CUSTOMER_ID INT,
PRODUCT_ID INT,
RATING INT,
REVIEW_TEXT VARCHAR(300),
REVIEW_DATE DATE,
	CONSTRAINT FK_CUSTOMER_REVIEW
		FOREIGN KEY(CUSTOMER_ID)
			REFERENCES CUSTOMER(CUSTOMER_ID),
	CONSTRAINT FK_PRODUCT_REVIEW
		FOREIGN KEY (PRODUCT_ID)
			REFERENCES PRODUCT(PRODUCT_ID)
);